In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cov.csv")

In [3]:
df.head()

,HalfHourId,Time,Value,Variable,AssetId,from,to,forecast,actual,index
0,1,2019-11-25 00:00:00,-100.0,power,abc123xyz,2019-11-24 23:30:00+00:00,2019-11-25 00:00:00+00:00,210,200,moderate
1,2,2019-11-25 00:30:00,0.0,power,abc123xyz,2019-11-25 00:00:00+00:00,2019-11-25 00:30:00+00:00,199,200,moderate
2,3,2019-11-25 01:00:00,0.0,power,abc123xyz,2019-11-25 00:30:00+00:00,2019-11-25 01:00:00+00:00,200,198,moderate
3,4,2019-11-25 01:30:00,-100.0,power,abc123xyz,2019-11-25 01:00:00+00:00,2019-11-25 01:30:00+00:00,204,189,moderate
4,5,2019-11-25 02:00:00,0.0,power,abc123xyz,2019-11-25 01:30:00+00:00,2019-11-25 02:00:00+00:00,199,191,moderate

In [4]:
df[(df["HalfHourId"] >= 14) & (df["HalfHourId"] <= 20)]

,HalfHourId,Time,Value,Variable,AssetId,from,to,forecast,actual,index
13,14,2019-11-25 06:30:00,0.0,power,abc123xyz,2019-11-25 06:00:00+00:00,2019-11-25 06:30:00+00:00,210,255,moderate
14,15,2019-11-25 07:00:00,0.0,power,abc123xyz,2019-11-25 06:30:00+00:00,2019-11-25 07:00:00+00:00,242,272,high
15,16,2019-11-25 07:30:00,0.0,power,abc123xyz,2019-11-25 07:00:00+00:00,2019-11-25 07:30:00+00:00,272,283,high
16,17,2019-11-25 08:00:00,0.0,power,abc123xyz,2019-11-25 07:30:00+00:00,2019-11-25 08:00:00+00:00,293,283,high
17,18,2019-11-25 08:30:00,0.0,power,abc123xyz,2019-11-25 08:00:00+00:00,2019-11-25 08:30:00+00:00,290,278,high
18,19,2019-11-25 09:00:00,0.0,power,abc123xyz,2019-11-25 08:30:00+00:00,2019-11-25 09:00:00+00:00,275,277,high
19,20,2019-11-25 09:30:00,0.0,power,abc123xyz,2019-11-25 09:00:00+00:00,2019-11-25 09:30:00+00:00,270,278,high